#!/bin/bash

# Script Name:                  copyAndAppend
# Author:                       David Prutch
# Date of latest revision:      05/31/2023
# Purpose:                      Copy system log to current working directory and append date and time to file name

# Declaration of variables

# Declaration of functions


# Main
###############
less /var/log/syslog > "syslog_$(date +%Y_%d_%m_%T)".txt


# End
